lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),


    path('', include('core.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (
    StudentCreateView,
    StudentDeleteView,
    StudentEditView,
    StudentListView,
)

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('edit/<uuid>', StudentEditView.as_view(), name='edit'),
    path('delete/<uuid>', StudentDeleteView.as_view(), name='delete'),
    # path('generate/', generate_students, name='generate'),
    ]

students/models.py
import random

from core.models import BaseModel, Person

from django.core.exceptions import ValidationError
from django.db import models

from faker import Faker

from groups.models import Group


class Student(BaseModel, Person):
    rating = models.SmallIntegerField(null=True, default=0)
    phone_number = models.CharField(max_length=15, null=True)
    group = models.ForeignKey(
        to=Group,
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    @staticmethod
    def generate_students(count):
        fake = Faker()
        result = []
        for _ in range(count):
            st = Student.objects.create(
                first_name=fake.first_name(),
                last_name=fake.last_name(),
                birthdate=fake.date(),
                rating=random.randint(0, 100),
                email=fake.email(),
                group=random.choice(list(Group.objects.all()))
            )
            result.append(st)
            st.save()
        return result

    def save(self, *args, **kwargs):
        phone_number = self.phone_number
        if phone_number:
            if not phone_number.isnumeric():
                raise ValidationError("VALUE ERROR: must be integer")

        super().save(*args, **kwargs)

students/forms.py
from django import forms

from students.models import Student


class StudentBaseForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'rating', 'email', 'phone_number', 'group']


class StudentCreateForm(StudentBaseForm):
    class Meta(StudentBaseForm.Meta):
        fields = ['first_name', 'last_name', 'rating', 'email']


class StudentEditForm(StudentBaseForm):
    class Meta(StudentBaseForm.Meta):
        fields = ['first_name', 'last_name', 'rating', 'email', 'phone_number', 'group']

students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from students.forms import StudentCreateForm, StudentEditForm
from students.models import Student


class StudentListView(ListView):
    paginate_by = 10
    page_kwarg = 'page'
    template_name = 'students-list.html'
    context_object_name = 'students'

    def get_queryset(self):
        students = Student.objects.select_related('group').all()
        params = ['first_name',
                  'last_name',
                  'rating']
        for param in params:
            value = self.request.GET.get(param)
            if value:
                students = students.filter(**{param: value})

        return students


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    form_class = StudentCreateForm
    template_name = 'students-create.html'
    success_url = reverse_lazy('students:list')


class StudentEditView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentEditForm
    template_name = 'students-edit.html'
    success_url = reverse_lazy('students:list')
    pk_url_kwarg = 'uuid'

    def get_object(self, queryset=None):
        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uuid=uuid)


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('students:list')
    pk_url_kwarg = 'uuid'

students/templates/students-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
<h1>Create student</h1>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}

      <input class="btn btn-info" type="submit" value="Create">
    </form>
{% endblock %}

students/templates/students-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
<h1>Edit student</h1>
{% endblock %}
{% block content %}

    <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class = "btn btn-success" type="submit" value="Save">
      <input class="btn btn-danger" formaction="{% url 'students:delete' student.uuid %}" type="submit" value="Delete">
    </form>

{% endblock %}

students/templates/students-list.html
{% extends 'base.html' %}
{% block header %}
<h1>Students list</h1>
{% endblock %}


{% block content %}

    <form>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">First name</span>
            </div>
      <input name="first_name" type="text" class="form-control" placeholder="Enter first name" aria-label="Username" aria-describedby="basic-addon1">
    </div>

        <div class="input-group mb-3">
  <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Last name</span>
      </div>
        <input name="last_name" type="text" class="form-control" placeholder="Enter last name" aria-label="Username" aria-describedby="basic-addon1">
        </div>


        <div class="input-group mb-3">
  <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Rating</span>
      </div>
        <input name="rating" type="text" class="form-control" placeholder="Enter rating" aria-label="Username" aria-describedby="basic-addon1">
        </div>


        <div class="mb-3">
      <input  class="btn btn-warning" type="submit" value="Search">
      <input class="btn btn-info" formaction="{% url 'students:create' %}" type="submit" value="Create">
        </div>
    </form>


 {% include 'includes/students-table.html' %}

{% endblock %}