groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupEditView, GroupListView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('edit/<int:id>', GroupEditView.as_view(), name='edit'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
    path('create/', GroupCreateView.as_view(), name='create'),
    ]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),


    path('', include('core.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

groups/models.py
import datetime
import random

from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

# Create your models here.
from teachers.models import Teacher


class Classroom(models.Model):
    name = models.CharField(max_length=32)
    floor = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(2), MaxValueValidator(5)]
    )

    def __str__(self):
        return f'{self.name}, {self.floor}'


class Group(models.Model):
    name = models.CharField(max_length=64, null=True)
    start_date = models.DateField(null=True, default=datetime.date.today)
    teacher = models.ForeignKey(
        to=Teacher,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups'
    )
    head = models.OneToOneField(
        to='students.Student',
        null=True,
        on_delete=models.SET_NULL,
        related_name='head_of_group'
    )
    classrooms = models.ManyToManyField(
        to=Classroom,
        related_name='groups'
    )

    def __str__(self):
        return f'{self.name}'

    @staticmethod
    def generate_group():
        group = Group(
            name=f'Group - {random.choice(range(5))}',
            course=random.choice([
                "LaunchCode's Discovery.",
                "Data Structures.",
                "Bioinformatics Algorithms.",
                "Linear Algebra: Problems and Methods.",
                "Kotlin.",
                "Atomic Kotlin.",
                "Easy Way to Technical Writing.",
                "Common English Verbs.",
            ]),
            teacher=random.choice(list(Teacher.objects.all()))
        )

        group.save()

    def clean(self):
        if self.head:
            if self.head not in self.students.all():
                raise ValidationError("Head of groups must be in group")

    def save(self, *args, **kwargs):
        # self.clean()
        super().save(*args, **kwargs)

groups/forms.py
from django import forms

from groups.models import Group


class GroupBaseForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class GroupCreateForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        fields = ['name', 'start_date', 'teacher']


class GroupEditForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        pass

groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from groups.forms import GroupCreateForm, GroupEditForm
from groups.models import Group


class GroupListView(ListView):
    paginate_by = 10
    page_kwarg = 'page'
    template_name = 'groups-list.html'
    context_object_name = 'groups'

    def get_queryset(self):
        groups = Group.objects.select_related('teacher', 'head').all()
        params = [
            'name',
            'course']
        for param in params:
            value = self.request.GET.get(param)
            if value:
                groups = groups.filter(**{param: value})

        return groups


class GroupEditView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = GroupEditForm
    template_name = 'groups-edit.html'
    success_url = reverse_lazy('groups:list')
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        id = self.kwargs.get('id')         # noqa
        return self.get_queryset().get(id=id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.object.students.all()
        return context


class GroupDeleteView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('groups:list')
    pk_url_kwarg = 'id'


class GroupCreateView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = GroupCreateForm
    template_name = 'groups-create.html'
    success_url = reverse_lazy('groups:list')

groups/templates/groups-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
<h1>Create group</h1>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-info" type="submit" value="Create">
    </form>
{% endblock %}

groups/templates/groups-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
<h1>Edit group</h1>
{% endblock %}
{% block content %}

    <form method="post">
        {% csrf_token %}

        {{form|crispy}}
<div class="mb-3">
      <input class = "btn btn-success" type="submit" value="Save">
      <input class="btn btn-danger" formaction="{% url 'groups:delete' group.id %}" type="submit" value="Delete">
    </div>
    </form>

{% include 'includes/students-table.html' %}

{% endblock %}

groups/templates/groups-list.html
{% extends 'base.html' %}
{% block header %}
<h1>Groups list</h1>
{% endblock %}

{% block content %}

    <form>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Name</span>
            </div>
      <input name="name" type="text" class="form-control" placeholder="Enter name" aria-label="Username" aria-describedby="basic-addon1">
    </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Course</span>
            </div>
      <input name="course" type="text" class="form-control" placeholder="Enter course" aria-label="Username" aria-describedby="basic-addon1">
    </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Start date</span>
            </div>
      <input name="start_date" type="text" class="form-control" placeholder="Enter start date" aria-label="Username" aria-describedby="basic-addon1">
    </div>


<!--      <label >Name:</label>-->
<!--      <input type="text" name="name"><br><br>-->

<!--      <label>Course:</label>-->
<!--      <input type="text" name="course"><br><br>-->

<!--      <label>Start date:</label>-->
<!--      <input type="text" name="start_date"><br><br>-->
<div class="mb-3">
      <input class="btn btn-warning" type="submit" value="Search">
      <input class="btn btn-info" formaction="{% url 'groups:create' %}" type="submit" value="Create">
    </div>
    </form>

<!--{{groups|safe}}-->
 {% include 'includes/groups-table.html' %}
{% endblock %}