lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),


    path('', include('core.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

teachers/urls.py
from django.urls import path

from teachers.views import TeacherCreateView, TeacherDeleteView, TeacherEditView, TeacherListView

app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list'),
    path('edit/<int:id>', TeacherEditView.as_view(), name='edit'),
    path('delete/<int:id>', TeacherDeleteView.as_view(), name='delete'),
    path('create/', TeacherCreateView.as_view(), name='create'),
    ]

teachers/models.py
# Create your models here.
from core.models import Person


class Teacher(Person):
    pass
    # first_name = models.CharField(max_length=64, null=False)
    # last_name = models.CharField(max_length=64, null=False)
    # birthdate = models.CharField(max_length=64, null=True, default=datetime.date.today)
    # email = models.EmailField(null=True, max_length=128)

    # def full_name(self):
    #     return f'{self.first_name} {self.last_name}'

    # def __str__(self):
    #     return f'{self.full_name()}'

teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeacherBaseForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'birthdate', 'email']


class TeacherCreateForm(TeacherBaseForm):
    class Meta(TeacherBaseForm.Meta):
        fields = ['first_name', 'last_name']


class TeacherEditForm(TeacherBaseForm):
    class Meta(TeacherBaseForm.Meta):
        fields = ['first_name', 'last_name', 'birthdate', 'email']

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect  # noqa
from django.shortcuts import render, get_object_or_404  # noqa
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from teachers.forms import TeacherCreateForm, TeacherEditForm
from teachers.models import Teacher


class TeacherListView(ListView):
    paginate_by = 10
    page_kwarg = 'page'
    template_name = 'teachers-list.html'
    context_object_name = 'teachers'

    def get_queryset(self):
        teachers = Teacher.objects.all()
        params = [
            'first_name',
            'last_name',
        ]
        for param in params:
            value = self.request.GET.get(param)
            if value:
                teachers = teachers.filter(**{param: value})

        return teachers


class TeacherEditView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = TeacherEditForm
    template_name = 'teachers-edit.html'
    success_url = reverse_lazy('teachers:list')
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        id = self.kwargs.get('id')    # noqa
        return self.get_queryset().get(id=id)

    def get_context_data(self, **kwargs):
        context = super(TeacherEditView, self).get_context_data(**kwargs)
        context['groups'] = self.object.groups.all()
        return context


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy('teachers:list')
    pk_url_kwarg = 'id'


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'teachers-create.html'
    success_url = reverse_lazy('teachers:list')

teachers/templates/teachers-create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
<h1>Create teacher</h1>
{% endblock %}
{% block content %}
    <form method="post">
        {% csrf_token %}

        {{form|crispy}}

      <input class="btn btn-info" type="submit" value="Create">
    </form>

{% endblock %}

teachers/templates/teachers-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block header %}
<h1>Edit teacher</h1>
{% endblock %}
{% block content %}

    <form method="post">
        {% csrf_token %}

        {{form|crispy}}
<div class="mb-3">
      <input class = "btn btn-success" type="submit" value="Save">
      <input class="btn btn-danger" formaction="{% url 'teachers:delete' teacher.id %}" type="submit" value="Delete">
    </div>
    </form>

{% include 'includes/groups-table.html' %}

{% endblock %}

teachers/templates/teachers-list.html
{% extends 'base.html' %}

{% block header %}
<h1>Teachers list</h1>
{% endblock %}
{% block content %}

    <form>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">First name</span>
            </div>
      <input name="first_name" type="text" class="form-control" placeholder="Enter first name" aria-label="Username" aria-describedby="basic-addon1">
    </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Last name</span>
            </div>
      <input name="last_name" type="text" class="form-control" placeholder="Enter last name" aria-label="Username" aria-describedby="basic-addon1">
    </div>

        <div class="input-group mb-3">
            <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">Email</span>
            </div>
      <input name="email" type="text" class="form-control" placeholder="Enter email" aria-label="Username" aria-describedby="basic-addon1">
    </div>

<div class="mb-3">
      <input class="btn btn-warning" type="submit" value="Search">
      <input class="btn btn-info" formaction="{% url 'teachers:create' %}" type="submit" value="Create">
    </div>
    </form>

{% if teachers %}
<table class="table table-striped table-dark">
    <thead>
    <tr>
        <th></th>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Email</th>
    </tr>
{% for teacher in teachers %}
    <tr>
    <td><a href="{% url 'teachers:edit' teacher.id %}" class="badge badge-secondary">EDIT</a></td>
    <td>{{ teacher.first_name }}</td>
    <td>{{ teacher.last_name }}</td>
    <td>{{ teacher.email }}</td>
        </tr>
<!--    <br>-->
{% endfor %}
</table>
{% include 'paginator.html' %}
{% else %}
<p>Sorry, list is empty </p>
{% endif %}
{% endblock %}