accounts/urls.py
from accounts.views import (AccountChangePasswordView,
                            AccountCreateView,
                            AccountLoginView,
                            AccountLogoutView,
                            AccountUpdateView)

from django.urls import path

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountCreateView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('password/', AccountChangePasswordView.as_view(), name='password'),
]

core/urls.py
from core.views import index

from django.urls import path


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    ]

groups/urls.py
from django.urls import path

from groups.views import GroupCreateView, GroupDeleteView, GroupEditView, GroupListView

app_name = 'groups'

urlpatterns = [
    path('', GroupListView.as_view(), name='list'),
    path('edit/<int:id>', GroupEditView.as_view(), name='edit'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
    path('create/', GroupCreateView.as_view(), name='create'),
    ]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),

    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('accounts/', include('accounts.urls')),


    path('', include('core.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (
    StudentCreateView,
    StudentDeleteView,
    StudentEditView,
    StudentListView,
)

app_name = 'students'

urlpatterns = [
    path('', StudentListView.as_view(), name='list'),
    path('create/', StudentCreateView.as_view(), name='create'),
    path('edit/<uuid>', StudentEditView.as_view(), name='edit'),
    path('delete/<uuid>', StudentDeleteView.as_view(), name='delete'),
    # path('generate/', generate_students, name='generate'),
    ]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    {% block title %}
    <title>LMS</title>
    {% endblock %}
</head>




<body>


<nav class="navbar navbar-expand-lg navbar-dark p-3 mb-2 bg-dark text-white">
  <div class="container">
  <a class="navbar-brand" href="{% url 'core:index' %}">LMS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"  aria-pressed="true">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">

          {% url 'students:list' as top_path %}
          {% if top_path == request.path %}
          <a class="nav-link active"  href="{% url 'students:list' %}">Students<span class="sr-only">(current)</span></a>
          {% else%}
          <a class="nav-link "  href="{% url 'students:list' %}">Students<span class="sr-only">(current)</span></a>
          {% endif %}
      </li>

      <li class="nav-item ">
          {% url 'groups:list' as top_path %}
          {% if top_path == request.path %}
         <a class="nav-link active" href="{% url 'groups:list' %}">Groups<span class="sr-only">(current)</span></a>
          {% else%}
          <a class="nav-link" href="{% url 'groups:list' %}">Groups<span class="sr-only">(current)</span></a>
          {% endif %}
        </li>

        <li class="nav-item">
            {% url 'teachers:list' as top_path %}
          {% if top_path == request.path %}
         <a class="nav-link active" href="{% url 'teachers:list' %}">Teachers<span class="sr-only">(current)</span></a>
          {% else%}
          <a class="nav-link" href="{% url 'teachers:list' %}">Teachers<span class="sr-only">(current)</span></a>
          {% endif %}
      </li>


<!--      </li>-->
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--          Dropdown-->
<!--        </a>-->
<!--        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--      </li>-->
    </ul>
      <ul class="navbar-nav ">
          {% if user.is_authenticated%}
          <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:profile' %}">Profile ({{user.username}})</a>
        </li>
             <div class="media">
            <div class="img-circle.vert">
    <img class="rounded-circle p-1 mb-0 " width="40" height="40" src="{{ user.profile.image.url }}" >
  </div>
  </div>
              <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
      </li>

        {% else%}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
      </li>
              <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
      </li>

              {% endif %}
    </ul>
  </div>
  </div>
</nav>
    <div class="container">
        {% include 'includes/messages.html' %}


        <div class=" border-0 rounded-bottom text-center h-3 p-2 mb-2 bg-secondary text-white shadow-lg p-3 mb-5 rounded">
            {% block header %}
            <h1>
                Welcome to LMS!
            </h1>

        {% endblock %}

    </div>





          {% block content %}

          {% endblock %}



    </div>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock %}

templates/paginator.html
<!--{% for contact in page_obj %}-->
<!--{% endfor %}-->
<!--{% if is_paginated %}-->
<!--        <nav aria-label="Pagination nav">-->
<!--            <ul class="pagination">-->
<!--                {# Back a page #}-->
<!--                {% if page_obj.has_previous %}-->
<!--                    <li class="page-item">-->
<!--                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&#10094;</a>-->
<!--                    </li>-->
<!--                {% else %}-->
<!--                    <li class="page-item disabled">-->
<!--                        <span class="page-link">&#10094;</span>-->
<!--                    </li>-->
<!--                {% endif %}-->
<!--                {# Page numbers #}-->
<!--                {% for i in paginator.page_range %}-->
<!--                    {% if page_obj.number == i %}-->
<!--                        <li class="page-item active">-->
<!--                            <span class="page-link">{{ i }}-->
<!--                                <span class="sr-only">(current)</span>-->
<!--                            </span>-->
<!--                        </li>-->
<!--                    {% else %}-->
<!--                        <li class="page-item">-->
<!--                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>-->
<!--                        </li>-->
<!--                    {% endif %}-->
<!--                {% endfor %}-->
<!--                {# Next page #}-->
<!--                {% if page_obj.has_next %}-->
<!--                    <li class="page-item">-->
<!--                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">&#10095;</a>-->
<!--                    </li>-->
<!--                {% else %}-->
<!--                    <li class="page-item disabled">-->
<!--                        <span class="page-link">&#10095;</span>-->
<!--                    </li>-->
<!--                {% endif %}-->
<!--            </ul>-->
<!--        </nav>-->
<!--    {% endif %}-->

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&{{ request.query_params }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&{{ request.query_params }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>